name: 🐛 Bug Report
description: File a bug report to help us improve Greater Components
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and resolve the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please check the following before submitting your bug report
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the troubleshooting guide
          required: true
        - label: I am using a supported version of Greater Components
          required: true
        - label: This issue is reproducible in a minimal example
          required: true

  - type: input
    id: version
    attributes:
      label: Greater Components Version
      description: What version of Greater Components are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Affected Package(s)
      description: Which Greater Components package is affected?
      options:
        - "@greater/primitives"
        - "@greater/fediverse"
        - "@greater/tokens"
        - "@greater/icons"
        - "@greater/utils"
        - "@greater/adapters"
        - "@greater/testing"
        - "Multiple packages"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code example that demonstrates the issue
      render: svelte
      placeholder: |
        <script>
          import { Button } from '@greater/primitives';
          // Your code that reproduces the issue
        </script>
        
        <Button onclick={handleClick}>Click me</Button>

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your development environment
      render: yaml
      placeholder: |
        OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        Node.js: [e.g. 20.0.0]
        Package Manager: [e.g. npm 10.0.0, pnpm 9.0.0]
        Browser: [e.g. Chrome 119, Firefox 120, Safari 17]
        Framework: [e.g. SvelteKit 2.0.0, Vite 5.0.0]
        TypeScript: [e.g. 5.2.0]
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Output
      description: Any relevant console errors or logs
      render: text
      placeholder: Paste any console errors here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain the problem

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "Low - Minor inconvenience"
        - "Medium - Affects functionality but has workaround"
        - "High - Breaks functionality with no workaround"
        - "Critical - Prevents usage of the component/library"
    validations:
      required: true

  - type: checkboxes
    id: accessibility
    attributes:
      label: Accessibility Impact
      description: Does this bug affect accessibility?
      options:
        - label: This bug affects keyboard navigation
        - label: This bug affects screen reader users
        - label: This bug affects color contrast/visibility
        - label: This bug affects focus management

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context or information about the problem
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute a fix?
      options:
        - label: I would be willing to submit a PR to fix this issue