<!--
Review.AttributionStrip - SSR-safe attribution for a shared draft under review

Shows `generatedBy`, `reviewedBy`, `reviewStatus`, and `editorNotes` so a
reviewer can see exactly what the agent did and what has most recently
happened, plus — when supplied — a plain-language statement of which approval
rules are in force and whether an outstanding invitation exists.

The review-status row is always qualified as "latest activity, not publication
state": `reviewStatus` is overwritten on every verdict submission upstream, so
neither it nor the verdict history is the publication gate. When Lesser marks
the newest recorded approval stale, the row shows the stale-approval state
instead — the approval stays visible as history, without the success tone or
wording of a current approval.

Empty fields are rendered with an explicit empty state by default rather than
being silently dropped: "not recorded" is itself information a reviewer needs.
-->

<script lang="ts">
	import { DefinitionList, DefinitionItem } from '@equaltoai/greater-components-primitives';
	import type { DraftReviewData, ReviewApprovalRequirement } from '../../types.js';
	import {
		REVIEW_STATE_QUALIFIER,
		formatReviewDateTime,
		resolveReviewState,
		reviewActorHandle,
		reviewActorName,
	} from './state.js';

	interface Props {
		/** The shared draft under review. */
		review: DraftReviewData;
		/**
		 * A description of the approval rule in force, for legibility.
		 *
		 * Build it with `describeApprovalRequirement(review)`. It is display-only:
		 * the strip never uses it to gate anything, and Lesser stays authoritative.
		 */
		approvalRequirement?: ReviewApprovalRequirement;
		/**
		 * Render fields that have no value with an explicit empty state.
		 *
		 * @defaultValue true
		 */
		showEmptyFields?: boolean;
		/** Visual density, forwarded to the underlying definition list. */
		density?: 'sm' | 'md';
		/** Custom CSS class. */
		class?: string;
	}

	let {
		review,
		approvalRequirement,
		showEmptyFields = true,
		density = 'sm',
		class: className = '',
	}: Props = $props();

	const stripClass = $derived(['gr-blog-review-attribution', className].filter(Boolean).join(' '));

	const generatedByName = $derived(reviewActorName(review.generatedBy));
	const generatedByHandle = $derived(reviewActorHandle(review.generatedBy));
	const generatedByAgent = $derived(Boolean(review.generatedBy?.isAgent));

	const reviewedByName = $derived(reviewActorName(review.reviewedBy));
	const reviewedByHandle = $derived(reviewActorHandle(review.reviewedBy));

	const state = $derived(resolveReviewState(review));
	const stateClass = $derived(
		`gr-blog-review-attribution__state gr-blog-review-attribution__state--${state.tone}`
	);

	const editorNotes = $derived(review.editorNotes?.trim() || '');

	const grantHandle = $derived(reviewActorHandle(review.grant?.reviewer));
	const grantedAt = $derived(formatReviewDateTime(review.grant?.grantedAt));

	// Names Lesser's rules without claiming progress against them: the active
	// The count is shown only when Lesser's canonical active-reviewer projection
	// (or an explicit consumer override) supplied it.
	const approvalText = $derived.by(() => {
		if (!approvalRequirement) return '';

		const { principalApproval, activeReviewerCount } = approvalRequirement;

		const reviewers =
			activeReviewerCount === undefined
				? 'every reviewer with an active invitation'
				: `all ${activeReviewerCount} reviewer${activeReviewerCount === 1 ? '' : 's'} with an active invitation`;

		return principalApproval
			? `Requires approval from ${reviewers}, and — because this draft records a generator — from the instance principal as well. Both are required.`
			: `Requires approval from ${reviewers}.`;
	});
</script>

<div class={stripClass}>
	<DefinitionList {density} dividers={false} class="gr-blog-review-attribution__list">
		{#if generatedByName || showEmptyFields}
			<DefinitionItem label="Generated by">
				{#if generatedByName}
					{#if generatedByAgent}
						<span class="gr-blog-review-attribution__agent-badge">Agent</span>
					{/if}
					<span class="gr-blog-review-attribution__actor-name">{generatedByName}</span>
					<span class="gr-blog-review-attribution__actor-handle">{generatedByHandle}</span>
				{:else}
					<span class="gr-blog-review-attribution__empty">Not recorded</span>
				{/if}
			</DefinitionItem>
		{/if}

		{#if reviewedByName || showEmptyFields}
			<DefinitionItem label="Reviewed by">
				{#if reviewedByName}
					<span class="gr-blog-review-attribution__actor-name">{reviewedByName}</span>
					<span class="gr-blog-review-attribution__actor-handle">{reviewedByHandle}</span>
				{:else}
					<span class="gr-blog-review-attribution__empty">Not yet reviewed</span>
				{/if}
			</DefinitionItem>
		{/if}

		<DefinitionItem label="Review status">
			<span class={stateClass}>{state.label}</span>
			{#if state.detail}
				<span class="gr-blog-review-attribution__state-detail">{state.detail}</span>
			{/if}
			{#if state.source !== 'none'}
				<span class="gr-blog-review-attribution__state-source">
					{REVIEW_STATE_QUALIFIER}
				</span>
			{/if}
		</DefinitionItem>

		{#if editorNotes || showEmptyFields}
			<DefinitionItem label="Editor notes">
				{#if editorNotes}
					<span class="gr-blog-review-attribution__notes">{editorNotes}</span>
				{:else}
					<span class="gr-blog-review-attribution__empty">None</span>
				{/if}
			</DefinitionItem>
		{/if}

		{#if grantHandle}
			<DefinitionItem label="Review invitation">
				<span class="gr-blog-review-attribution__actor-handle">{grantHandle}</span>
				{#if grantedAt.label}
					<span class="gr-blog-review-attribution__granted-at">
						invited <time datetime={grantedAt.iso}>{grantedAt.label}</time>
					</span>
				{/if}
				<span class="gr-blog-review-attribution__revocable">Invitations can be revoked.</span>
			</DefinitionItem>
		{/if}

		{#if approvalText}
			<DefinitionItem label="Approval required">
				<span class="gr-blog-review-attribution__approval">{approvalText}</span>
			</DefinitionItem>
		{/if}
	</DefinitionList>
</div>
