/**
 * @equaltoai/greater-components-adapters - Transport adapters and state management for Fediverse protocols
 */
import type { AiAnalysisQuery } from './graphql';
export type AIAnalysis = NonNullable<AiAnalysisQuery['aiAnalysis']>;
export {
	AUTH_EXPIRED_CODE,
	UNAUTHENTICATED_CODE,
	AuthExpiredError,
	createSingleFlightRefresh,
	extractServerErrorCodes,
	hasServerErrorCode,
	isAuthExpiredError,
} from './authExpiry.js';
export type { AuthExpiredHandler, AuthExpiredReason, TokenRefreshCallback } from './authExpiry.js';
export { WebSocketClient } from './WebSocketClient';
export { SseClient } from './SseClient';
export { HttpPollingClient } from './HttpPollingClient';
export { TransportFallback } from './TransportFallback';
export { TransportManager } from './TransportManager';
export { WebSocketPool, getGlobalWebSocketPool, resetGlobalWebSocketPool } from './WebSocketPool';
export type { WebSocketPoolConfig, PooledWebSocket } from './WebSocketPool';
export {
	createGraphQLClient,
	getGraphQLClient,
	closeGraphQLClient,
	LesserGraphQLAdapter,
	LesserGraphQLAdapterError,
	createLesserGraphQLAdapter,
	createSubmitDraftReviewHandler,
	isDraftReviewShareConflict,
	typePolicies,
	cacheConfig,
	evictStaleCache,
	limitCacheSize,
	optimistic,
} from './graphql';
export type {
	GraphQLClientConfig,
	GraphQLClientInstance,
	LesserGraphQLAdapterConfig,
	DraftReviewSubmission,
	ShareDraftForReviewOutcome,
	SharedDraftReview,
	TimelineVariables,
	CreateNoteVariables,
	ConversationMessagesVariables,
	CreateConversationVariables,
	CreateQuoteNoteMutationVariables,
	SearchVariables,
	SendMessageVariables,
	UpdateMediaVariables,
	Visibility,
	NotificationLevel,
	ObjectFieldsFragment,
	Actor,
	ViewerQuery,
	QuoteType,
	UploadMediaInput,
	MediaCategory,
	MediaType,
	UploadMediaMutationVariables,
	UploadMediaMutation,
	UploadMediaPayload,
	SharedDraftReviewsQuery,
	SharedDraftReviewsQueryVariables,
	DraftReviewVerdict,
} from './graphql';
export { LesserSoulClient, LesserSoulClientError, createLesserSoulClient } from './lesser/index.js';
export type {
	LesserFetchLike,
	LesserAgent,
	LesserSoulAgentIdentity,
	LesserSoulAgentBinding,
	LesserSoulBodyBinding,
	LesserSoulClientConfig,
	LesserSoulIncorporateResponse,
	LesserSoulInventoryItem,
	LesserSoulsMineResponse,
} from './lesser/index.js';
export {
	LesserHostSoulClient,
	HostedSoulBootstrapClient,
	LesserHostSoulClientError,
	SoulBootstrapClient,
	SoulBootstrapClientError,
	SoulBootstrapSigningPlanError,
	canPublishHostedSoulBootstrap,
	createHostedSoulBootstrapClient,
	createLesserHostSoulClient,
	createSoulBootstrapClient,
	createSoulBootstrapSigningPlan,
	createSoulBootstrapSigningPlans,
	getHostedSoulBootstrapTerminalDeclarationEvidenceSummary,
	getHostedSoulBootstrapTerminalDeclarationEvidence,
	getHostedSoulGenesisComposerState,
	getHostedSoulGenesisConversation,
	hasHostedSoulBootstrapTerminalDeclarationEvidence,
	isHostedSoulBootstrapDeclarationReady,
	isHostedSoulBootstrapInProgress,
	isHostedSoulBootstrapPublishReady,
	normalizeSoulBootstrapError,
	resolveSoulAgentIdFromEnsTextRecord,
} from './soul/index.js';
export type {
	ErrorEnvelope as LesserHostErrorEnvelope,
	LesserHostSoulClientConfig,
	ResolveEnsOptions,
	SoulAgentMintConversationsQuery,
	SoulAgentMintConversationsResponse,
	SoulAgentCommActivityItem,
	SoulAgentCommActivityQuery,
	SoulAgentCommActivityResponse,
	SoulAgentChannelsResponse,
	SoulAgentChannelPreferencesRequest,
	SoulAgentChannelPreferencesResponse,
	SoulAgentCommQueueItem,
	SoulAgentCommQueueQuery,
	SoulAgentCommQueueResponse,
	SoulAgentIdentity,
	SoulAnchorAssurance,
	SoulAnchorEvidence,
	SoulCommSendErrorEnvelope,
	SoulCommSendRequest,
	SoulCommSendResponse,
	SoulCommStatusErrorEnvelope,
	SoulCommStatusResponse,
	SoulMintConversation,
	SoulMintConversationCompleteRequest,
	SoulMintConversationFinalizeBeginRequest,
	SoulMintConversationFinalizePreflightResponse,
	SoulMintConversationFinalizeRequest,
	SoulMintConversationFinalizeResponse,
	SoulMintConversationSSEInput,
	SoulResolveResponse,
	SoulSearchQuery,
	SoulSearchResponse,
	SoulSearchResult,
	BeginSoulBootstrapInput,
	CompleteHostedSoulGenesisInput,
	CompleteSoulBootstrapConversationInput,
	FinalizeSoulBootstrapInput,
	HostedGenesisConversationSummary,
	HostedGenesisConversationSummaryResult,
	HostedSoulBootstrapActionableError,
	HostedSoulBootstrapAnchorState,
	HostedSoulBootstrapAuthorityModel,
	HostedSoulBootstrapAvailableAction,
	HostedSoulBootstrapBoundSoulEvidence,
	HostedSoulBootstrapClientConfig,
	HostedSoulBootstrapCompactTerminalDeclarationEvidence,
	HostedSoulBootstrapCurrentInput,
	HostedSoulBootstrapDeclarationPreview,
	HostedSoulBootstrapGraphQLHostedGenesisConversation,
	HostedSoulBootstrapGraphQLHostedGenesisMessage,
	HostedSoulBootstrapHostRequestMetadata,
	HostedSoulBootstrapMode,
	HostedSoulBootstrapMutationPayload,
	HostedSoulBootstrapMutationResult,
	HostedSoulBootstrapNextAction,
	HostedSoulBootstrapPhase,
	HostedSoulBootstrapPublicationEvidence,
	HostedSoulBootstrapRecoveryAction,
	HostedSoulBootstrapRecoveryCategory,
	HostedSoulBootstrapResult,
	HostedSoulBootstrapState,
	HostedSoulBootstrapStateModel,
	HostedSoulBootstrapSurface,
	HostedSoulBootstrapStatusSource,
	HostedSoulBootstrapTerminalDeclaration,
	HostedSoulBootstrapTerminalDeclarationCheckpointName,
	HostedSoulBootstrapTerminalDeclarationEvidence,
	HostedSoulBootstrapTerminalDeclarationEvidenceOptions,
	HostedSoulBootstrapTerminalDeclarationEvidenceSource,
	HostedSoulBootstrapTerminalDeclarationEvidenceSummary,
	HostedSoulGenesisComposerState,
	HostedSoulGenesisConversationMessage,
	HostedSoulGenesisConversationStatus,
	HostedSoulGenesisConversationTranscript,
	LesserHostHostedGenesisConversation,
	LesserHostHostedGenesisConversationResponse,
	PrepareSoulBootstrapFinalizeInput,
	PrepareSoulBootstrapPrincipalDeclarationInput,
	PublishHostedSoulInput,
	RecoverHostedSoulGenesisTurnInput,
	RestartSoulBootstrapInput,
	SendHostedSoulGenesisMessageInput,
	SendSoulBootstrapConversationMessageInput,
	SoulBootstrapActionableError,
	SoulBootstrapClientConfig,
	SoulBootstrapCorrelationState,
	SoulBootstrapCurrentInput,
	SoulBootstrapErrorCategory,
	SoulBootstrapErrorState,
	SoulBootstrapGraphQLClient,
	SoulBootstrapGraphQLError,
	SoulBootstrapMutationPayload,
	SoulBootstrapMutationResult,
	SoulBootstrapPhase,
	SoulBootstrapPublicationEvidence,
	SoulBootstrapResult,
	SoulBootstrapFinalizeRequestTemplate,
	SoulBootstrapFinalizeSigningPlan,
	SoulBootstrapHexBytesSigningInstruction,
	SoulBootstrapHexString,
	SoulBootstrapMessageEncoding,
	SoulBootstrapPrincipalDeclarationSigningPlan,
	SoulBootstrapPrincipalDeclarationSubmitInput,
	SoulBootstrapSigningCheckpoint,
	SoulBootstrapSigningMethod,
	SoulBootstrapSigningPlan,
	SoulBootstrapSigningPlanErrorCode,
	SoulBootstrapSigningPlanErrorOptions,
	SoulBootstrapSigningPlanKind,
	SoulBootstrapSigningPlanSource,
	SoulBootstrapState,
	SoulBootstrapSurface,
	SoulBootstrapUtf8SigningInstruction,
	SoulBootstrapWalletChallengeSigningPlan,
	SoulBootstrapWalletSigningInstruction,
	StartHostedSoulBootstrapInput,
	VerifySoulBootstrapPrincipalDeclarationInput,
	VerifySoulBootstrapWalletInput,
} from './soul/index.js';
export { createLesserMessagesHandlers } from './messaging/index.js';
export type { LesserMessagesAdapter, LesserMessagesHandlersConfig } from './messaging/index.js';
export {
	createTimelineStore,
	createNotificationStore,
	createPresenceStore,
	createBrowserPresenceActivitySource,
	createBrowserPresenceLocationSource,
} from './stores';
export { AdminStreamingStore, createAdminStreamingStore } from './stores/adminStreamingStore';
export type {
	MetricsUpdate,
	ModerationAlert,
	CostAlert,
	BudgetAlert,
	FederationHealthUpdate,
	ModerationQueueItem,
	ThreatIntelligence,
	PerformanceAlert,
	InfrastructureEvent,
	AdminStreamingStoreState,
	AdminStreamingStoreConfig,
} from './stores/adminStreamingStore';
export {
	unifiedStatusToTimelineItem,
	unifiedStatusesToTimelineItems,
} from './stores/unifiedToTimeline';
export {
	unifiedNotificationToStoreNotification,
	unifiedNotificationsToStoreNotifications,
} from './stores/unifiedToNotification';
export {
	StreamingOperationsManager,
	TimelineStreamingHandler,
	NotificationStreamingHandler,
	AccountStreamingHandler,
	DeleteStreamingHandler,
	EditStreamingHandler,
	StreamingStateManager,
} from './streaming/operations';
export type {
	StreamingOperation,
	StreamingOperationHandler,
	StreamingState,
	StreamingConfig,
} from './streaming/operations';
export {
	mapMastodonAccount,
	mapMastodonStatus,
	mapMastodonNotification,
	mapMastodonStreamingEvent,
	batchMapMastodonAccounts,
	batchMapMastodonStatuses,
	batchMapMastodonNotifications,
	mapLesserAccount,
	mapLesserPost,
	mapLesserNotification,
	mapLesserStreamingUpdate,
	handleLesserGraphQLResponse,
	mapLesserTimelineConnection,
	batchMapLesserAccounts,
	batchMapLesserPosts,
	batchMapLesserNotifications,
	mapLesserObject,
	convertGraphQLObjectToLesser,
	MapperUtils,
} from './mappers';
export type {
	BaseTransportConfig,
	TransportAdapter,
	TransportFallbackConfig,
	TransportType,
	TransportManagerConfig,
	TransportManagerState,
	TransportSwitchEvent,
	TransportEventMap,
	TransportEventName,
	WebSocketClientConfig,
	WebSocketClientState,
	WebSocketMessage,
	WebSocketEvent,
	WebSocketEventType,
	WebSocketEventHandler,
	AuthExpiredEventData,
	SseClientConfig,
	SseClientState,
	SseMessage,
	HttpPollingClientConfig,
	HttpPollingClientState,
	HttpPollingMessage,
	HeartbeatMessage,
	LatencySample,
} from './types';
export type {
	TimelineStore,
	NotificationStore,
	PresenceStore,
	PresenceActivitySource,
	PresenceLocationSource,
	BrowserPresenceActivitySourceOptions,
	BrowserPresenceLocationSourceOptions,
	BaseStore,
	StoreFactory,
	TimelineItem,
	TimelineState,
	TimelineConfig,
	Notification,
	NotificationState,
	NotificationConfig,
	NotificationFilter,
	NotificationAction,
	LesserTimelineMetadata,
	LesserNotificationMetadata,
	UserPresence,
	SessionInfo,
	PresenceState,
	PresenceConfig,
	StreamingEdit,
	JsonPatch,
} from './stores/types';
export type {
	UnifiedAccount,
	UnifiedStatus,
	UnifiedNotification,
	SourceMetadata,
	MediaAttachment,
	MediaMeta,
	Mention,
	Tag,
	TagHistory,
	CustomEmoji,
	Poll,
	PollOption,
	AccountField,
	AccountRelationship,
	AdminReport,
	StreamingUpdate,
	StreamingDelete,
	StreamingEdit as UnifiedStreamingEdit,
	MappingError,
	MapperResult,
	BatchMapperResult,
	ValidationRule,
	FieldValidator,
} from './mappers';
export type {
	MastodonAccount,
	MastodonField,
	MastodonEmoji,
	MastodonRelationship,
	MastodonStatus,
	MastodonMediaAttachment,
	MastodonMediaMeta,
	MastodonMention,
	MastodonTag,
	MastodonTagHistory,
	MastodonPreviewCard,
	MastodonPoll,
	MastodonPollOption,
	MastodonNotification,
	MastodonReport,
	MastodonStreamingEvent,
	MastodonInstance,
	MastodonRule,
	MastodonError,
	MastodonPaginationParams,
	MastodonPaginatedResponse,
} from './mappers';
export type {
	LesserGraphQLResponse,
	LesserGraphQLError,
	LesserAccountFragment,
	LesserProfileField,
	LesserEmojiFragment,
	LesserRelationshipFragment,
	LesserPostFragment,
	LesserInteractionCounts,
	LesserUserInteractions,
	LesserMediaFragment,
	LesserMediaMetadata,
	LesserMentionFragment,
	LesserHashtagFragment,
	LesserTrendingData,
	LesserPollFragment,
	LesserPollOption,
	LesserNotificationFragment,
	LesserAdminReportFragment,
	LesserTimelineConnection,
	LesserTimelineEdge,
	LesserPageInfo,
	LesserStreamingUpdate,
	LesserStreamingData,
	LesserPostStreamingData,
	LesserNotificationStreamingData,
	LesserAccountStreamingData,
	LesserDeleteStreamingData,
	LesserGetTimelineQuery,
	LesserGetTimelineVariables,
	LesserGetNotificationsQuery,
	LesserGetNotificationsVariables,
	LesserCreatePostMutation,
	LesserCreatePostVariables,
	LesserInstanceInfo,
	LesserValidationError,
	LesserMutationError,
	LesserTimelineSubscription,
	LesserNotificationSubscription,
} from './mappers';
export type {
	LesserReputationFragment,
	LesserVouchFragment,
	LesserCommunityNoteFragment,
	LesserQuoteContextFragment,
	LesserAIAnalysisFragment,
} from './mappers/lesser/types.js';
//# sourceMappingURL=index.d.ts.map
